// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment_Management_System.Models;

namespace Payment_Management_System.Migrations
{
    [DbContext(typeof(PaymentContext))]
    [Migration("20190922093231_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payment_Management_System.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<decimal>("PaymentSum");

                    b.Property<int>("PaymentType");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Payment_Management_System.Models.PaymentPosition", b =>
                {
                    b.Property<int>("PaymentPositionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("NestedFileName");

                    b.Property<string>("NestedFilePath");

                    b.Property<int>("PaymentId");

                    b.Property<decimal>("PaymentPositionSum");

                    b.HasKey("PaymentPositionId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentPosition");
                });

            modelBuilder.Entity("Payment_Management_System.Models.PaymentPosition", b =>
                {
                    b.HasOne("Payment_Management_System.Models.Payment", "Payment")
                        .WithMany("PaymentPositions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
